name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thankyou for helping us to improve towards more quality standards. We will respond to this your's as soon as possible"
        pr-message: "Thankyou 💖 for improving this list. We'll reach you out soon."
